import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainProviders from '@/app/providers/MainProviders/MainProviders'

import './styles/variables/globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<MainProviders>
				<body className={inter.className}>{children}</body>
			</MainProviders>
		</html>
	)
}
